# Generated by Django 3.0.8 on 2020-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='comments',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
